### ISSUE TITLE
I am getting error in backend-api while typing in search term-in complex-react-app

### ISSUE THREAD

**Issue by PagoluSrikar** [LearnWebCode/react-course#5]
Please.. anyone help me to resolve it..
using ubuntu os 

(node:23022) UnhandledPromiseRejectionWarning: MongoError: FieldPath field names may not start with '$'.
    at MessageStream.messageHandler (/home/srikar/Desktop/backend-api/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (/home/srikar/Desktop/backend-api/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/srikar/Desktop/backend-api/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at TLSSocket.ondata (internal/streams/readable.js:719:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23022) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23022) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by alexmisnovs** [comment]
Hey dude, I have answered this on udemy.

https://www.udemy.com/course/react-for-the-rest-of-us/learn/lecture/19689368#questions/13939076

still works

**Comment by PagoluSrikar** [comment]
I tried that too but not working bro..

(node:7086) UnhandledPromiseRejectionWarning: MongoError: FieldPath field names may not start with '$'.
    at MessageStream.messageHandler (/home/srikar/Desktop/backend-api/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:314:20)
    at processIncomingData (/home/srikar/Desktop/backend-api/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/srikar/Desktop/backend-api/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at MessageStream.Writable.write (_stream_writable.js:318:11)
    at TLSSocket.ondata (_stream_readable.js:718:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
(node:7086) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7086) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


Getting this error.
I am facing this issue only while typing in search term.

**Comment by alexmisnovs** [comment]
Hey dude, maybe try deleting your node_modules and then run npm install again.

**Comment by PagoluSrikar** [comment]
I tried that too.. still same problem

**Comment by PagoluSrikar** [comment]
any one please help me i am unable to solve that error still now


srikar@srikar-Aspire-E1-571G:~/Desktop/backend-api$ npm run start

> complex-app@1.0.0 start /home/srikar/Desktop/backend-api
> node db

(node:19964) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19964) UnhandledPromiseRejectionWarning: MongoError: FieldPath field names may not start with '$'.
    at MessageStream.messageHandler (/home/srikar/Desktop/backend-api/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (/home/srikar/Desktop/backend-api/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/srikar/Desktop/backend-api/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at TLSSocket.ondata (internal/streams/readable.js:719:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
(node:19964) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BobRoyAce** [comment]
I had the same issue and have gotten no answer. Does the instructor even check the questions?

**Comment by esradev** [comment]
hi there. I have same error:
PS E:\React For The Rest Of Us\backend-api> npm run start

> complex-app@1.0.0 start E:\React For The Rest Of Us\backend-api
> node db

(node:6380) UnhandledPromiseRejectionWarning: MongoError: FieldPath field names may not start with '$'.
    at MessageStream.messageHandler (E:\React For The Rest Of Us\backend-api\node_modules\mongodb\lib\cmap\connection.js:268:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (E:\React For The Rest Of Us\backend-api\node_modules\mongodb\lib\cmap\message_stream.js:144:12)
    at MessageStream._write (E:\React For The Rest Of Us\backend-api\node_modules\mongodb\lib\cmap\message_stream.js:42:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at TLSSocket.ondata (_stream_readable.js:719:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated
either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by geeqib23** [comment]
I am not getting any error, but on launching the Post request through postman, instead of the expected result i am getting an empty array as response
There is something wrong in the backend-api i think.

**Comment by LearnWebCode** [comment]
Hello everyone, I just pushed a fix to this, found in the following file:

[https://github.com/LearnWebCode/react-course/blob/master/backend-api/models/Post.js](https://github.com/LearnWebCode/react-course/blob/master/backend-api/models/Post.js)

In the newest version of the MongoDB system itself (local or Atlas Cloud Service, not our NPM package) we don't want to use $sort before $project if we're sorting by a search's textScore. Simply updating the file I linked to above with the latest version will fix this issue.

If you're seeing other errors related to search and the backend, it's possible you didn't create the indexes properly for the title and body fields.

Thanks!
Brad

**Comment by geeqib23** [comment]
```
(node:36811) UnhandledPromiseRejectionWarning: MongoError: text index required for $text query
    at MessageStream.messageHandler (/home/geeqib23/Desktop/ReactLearn - Copy/backend-api/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:198:13)
    at processIncomingData (/home/geeqib23/Desktop/ReactLearn - Copy/backend-api/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/geeqib23/Desktop/ReactLearn - Copy/backend-api/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at MessageStream.Writable.write (_stream_writable.js:299:11)
    at TLSSocket.ondata (_stream_readable.js:710:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
(node:36811) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:36811) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:36811) UnhandledPromiseRejectionWarning: MongoError: text index required for $text query
    at MessageStream.messageHandler (/home/geeqib23/Desktop/ReactLearn - Copy/backend-api/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:198:13)
    at processIncomingData (/home/geeqib23/Desktop/ReactLearn - Copy/backend-api/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/geeqib23/Desktop/ReactLearn - Copy/backend-api/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at MessageStream.Writable.write (_stream_writable.js:299:11)
    at TLSSocket.ondata (_stream_readable.js:710:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
(node:36811) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

**Comment by geeqib23** [comment]
`(node:36811) UnhandledPromiseRejectionWarning: MongoError: text index required for $text query
    at MessageStream.messageHandler (/home/geeqib23/Desktop/ReactLearn - Copy/backend-api/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:198:13)
    at processIncomingData (/home/geeqib23/Desktop/ReactLearn - Copy/backend-api/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/geeqib23/Desktop/ReactLearn - Copy/backend-api/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at MessageStream.Writable.write (_stream_writable.js:299:11)
    at TLSSocket.ondata (_stream_readable.js:710:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
(node:36811) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:36811) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:36811) UnhandledPromiseRejectionWarning: MongoError: text index required for $text query
    at MessageStream.messageHandler (/home/geeqib23/Desktop/ReactLearn - Copy/backend-api/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:198:13)
    at processIncomingData (/home/geeqib23/Desktop/ReactLearn - Copy/backend-api/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/geeqib23/Desktop/ReactLearn - Copy/backend-api/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at MessageStream.Writable.write (_stream_writable.js:299:11)
    at TLSSocket.ondata (_stream_readable.js:710:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
(node:36811) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)`
Getting this error now after updating the Post model.

**Comment by LearnWebCode** [comment]
@geeqib23 it looks like you need to create text indexes on the **title** and **body** fields for the posts collection in the database. I can't remember the exact timestamp, but in the video where we start working on the backend of the search feature; you can drag your mouse along the timeline and see a preview of the scene; you're looking for a moment where I'm in the MongoDB Atlas site; you can see how to create the indexes.
